programa5_2: programa5-2.cpp PoligonoIrreg.o
	g++ programa5-2.cpp PoligonoIrreg.o Coordenada.o -o 5-2

PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c

Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
