/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

long  inicializa_random_1_arg = 0;
int itera;

void rand_prog_1(char *host) {
	CLIENT *clnt;
	void  *result_1;
	double  *result_2;
	char *obtiene_siguiente_random_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

  //inicializa_random(misemilla);
	result_1 = inicializa_random_1(&inicializa_random_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

  for(int i = 0; i < itera; i++) {
    result_2 = obtiene_siguiente_random_1((void*)&obtiene_siguiente_random_1_arg, clnt);
    printf("%d : %d\n", i, (int) *result_2);

    if (result_2 == (double *) NULL) {
  		clnt_perror (clnt, "call failed");
  	}
  }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
  // ****************

  if(argc != 4) {
     fprintf(stderr, "Uso: %s server_host semilla iteraciones\n", argv[0]);
     exit(1);
  }

  inicializa_random_1_arg = (long)atoi(argv[2]);
  itera = atoi(argv[3]);
  // ****************
	host = argv[1];

	rand_prog_1 (host);

  exit (0);
}
