/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

double a, b;

void
rand_prog_1(char *host)
{
	CLIENT *clnt;
	datos  *result_1;
	datos  suma_1_arg;
	datos  *result_2;
	datos  producto_1_arg;
	datos  *result_3;
	datos  cociente_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
  suma_1_arg.a = a;
  suma_1_arg.b = b;
  producto_1_arg.a = a;
  producto_1_arg.b = b;
  cociente_1_arg.a = a;
  cociente_1_arg.b = b;

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (datos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = producto_1(&producto_1_arg, clnt);
	if (result_2 == (datos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = cociente_1(&cociente_1_arg, clnt);
	if (result_3 == (datos *) NULL) {
		clnt_perror (clnt, "call failed");
	}

  /* Print */
  printf("Suma: %f, %s\n", result_1->r, result_1->message);
  printf("Producto: %f, %s\n", result_2->r, result_2->message);
  printf("Cociente: %f, %s\n", result_3->r, result_3->message);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host num1 num2\n", argv[0]);
		exit (1);
	}

	host = argv[1];
  a = atof(argv[2]);
  b = atof(argv[3]);

	rand_prog_1 (host);
exit (0);
}
