/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RAND_H_RPCGEN
#define _RAND_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct datos {
	double a;
	double b;
	double r;
	char message[100];
};
typedef struct datos datos;

#define RAND_PROG 0x31111111
#define RAND_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  datos * suma_1(datos *, CLIENT *);
extern  datos * suma_1_svc(datos *, struct svc_req *);
#define PRODUCTO 2
extern  datos * producto_1(datos *, CLIENT *);
extern  datos * producto_1_svc(datos *, struct svc_req *);
#define COCIENTE 3
extern  datos * cociente_1(datos *, CLIENT *);
extern  datos * cociente_1_svc(datos *, struct svc_req *);
extern int rand_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  datos * suma_1();
extern  datos * suma_1_svc();
#define PRODUCTO 2
extern  datos * producto_1();
extern  datos * producto_1_svc();
#define COCIENTE 3
extern  datos * cociente_1();
extern  datos * cociente_1_svc();
extern int rand_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos (XDR *, datos*);

#else /* K&R C */
extern bool_t xdr_datos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RAND_H_RPCGEN */
