.PHONY: exec
exec: Main.class
	@echo "========================="
	@echo "Executing..."
	@java Main
	@echo "\n"

Main.class: Main.java
	@echo "========================="
	@echo "Compiling..."
	@javac Main.java
	@echo "Done.\n"
